name: Create Entry
description: Create a new podcast entry
title: "create: a new RSS feed entry"
labels:
- create
body:
  - type: markdown
    attributes:
      value: |
        # Request to create a new RSS feed entry

        If you haven't yet, you'll need to upload any audio/image files;
        you can use the link below:

        [Upload Attachments here](../upload/uploads/dist/uploads)
  - type: dropdown
    id: feed_title_clean
    validations:
      required: true
    attributes:
      label: Feed
      description: Which feed are you adding the episode for?
      multiple: false
      options: []
  - type: input
    id: title
    attributes:
      label: Title
      description: What is the episode called?
      placeholder: My Episode
    validations:
      required: true
  - type: dropdown
    id: attachment
    validations:
      required: true
    attributes:
      label: Attachment
      description: Which file are you attaching?
      multiple: false
      options: []
  - type: dropdown
    id: artwork
    validations:
      required: false
    attributes:
      label: Artwork
      description: Is there a cover image?
      multiple: false
      options: []
  - type: textarea
    id: description
    attributes:
      label: Description
      description: How would you describe the episode?
    validations:
      required: true
  - type: dropdown
    id: category
    validations:
      required: true
    attributes:
      label: Category
      description: What is the primary category?
      multiple: false
      options:
      - Arts
      - Arts; Books
      - Arts; Design
      - Arts; Fashion & Beauty
      - Arts; Food
      - Arts; Performing Arts
      - Arts; Visual Arts
      - Business
      - Business; Careers
      - Business; Entrepreneurship
      - Business; Investing
      - Business; Management
      - Business; Marketing
      - Business; Non-Profit
      - Comedy
      - Comedy; Comedy Interviews
      - Comedy; Improv
      - Comedy; Stand-Up
      - Education
      - Education; Courses
      - Education; How To
      - Education; Language Learning
      - Education; Self-Improvement
      - Fiction
      - Fiction; Comedy Fiction
      - Fiction; Drama
      - Fiction; Science Fiction
      - Government
      - History
      - Health & Fitness
      - Health & Fitness; Alternative Health
      - Health & Fitness; Fitness
      - Health & Fitness; Medicine
      - Health & Fitness; Mental Health
      - Health & Fitness; Nutrition
      - Health & Fitness; Sexuality
      - Kids & Family
      - Kids & Family; Education for Kids
      - Kids & Family; Parenting
      - Kids & Family; Pets & Animals
      - Kids & Family; Stories for Kids
      - Leisure
      - Leisure; Animation & Manga
      - Leisure; Automotive
      - Leisure; Aviation
      - Leisure; Crafts
      - Leisure; Games
      - Leisure; Hobbies
      - Leisure; Home & Garden
      - Leisure; Video Games
      - Music
      - Music; Music Commentary
      - Music; Music History
      - Music; Music Interviews
      - News
      - News; Business News
      - News; Daily News
      - News; Entertainment News
      - News; News Commentary
      - News; Politics
      - News; Sports News
      - News; Tech News
      - Religion & Spirituality
      - Religion & Spirituality; Buddhism
      - Religion & Spirituality; Christianity
      - Religion & Spirituality; Hinduism
      - Religion & Spirituality; Islam
      - Religion & Spirituality; Judaism
      - Religion & Spirituality; Religion
      - Religion & Spirituality; Spirituality
      - Science
      - Science; Astronomy
      - Science; Chemistry
      - Science; Earth Sciences
      - Science; Life Sciences
      - Science; Mathematics
      - Science; Natural Sciences
      - Science; Nature
      - Science; Physics
      - Science; Social Sciences
      - Society & Culture
      - Society & Culture; Documentary
      - Society & Culture; Personal Journals
      - Society & Culture; Philosophy
      - Society & Culture; Places & Travel
      - Society & Culture; Relationships
      - Sports
      - Sports; Baseball
      - Sports; Basketball
      - Sports; Cricket
      - Sports; Fantasy Sports
      - Sports; Football
      - Sports; Golf
      - Sports; Hockey
      - Sports; Rugby
      - Sports; Soccer
      - Sports; Swimming
      - Sports; Tennis
      - Sports; Volleyball
      - Sports; Wilderness
      - Sports; Wrestling
      - Technology
      - True Crime
      - TV & Film
      - TV & Film; After Shows
      - TV & Film; Film History
      - TV & Film; Film Interviews
      - TV & Film; TV Reviews
      - TV & Film; Film Reviews
  - type: dropdown
    id: categories
    validations:
      required: false
    attributes:
      label: Categories
      description: What is the secondary categories?
      multiple: true
      options:
      - Arts
      - Arts; Books
      - Arts; Design
      - Arts; Fashion & Beauty
      - Arts; Food
      - Arts; Performing Arts
      - Arts; Visual Arts
      - Business
      - Business; Careers
      - Business; Entrepreneurship
      - Business; Investing
      - Business; Management
      - Business; Marketing
      - Business; Non-Profit
      - Comedy
      - Comedy; Comedy Interviews
      - Comedy; Improv
      - Comedy; Stand-Up
      - Education
      - Education; Courses
      - Education; How To
      - Education; Language Learning
      - Education; Self-Improvement
      - Fiction
      - Fiction; Comedy Fiction
      - Fiction; Drama
      - Fiction; Science Fiction
      - Government
      - History
      - Health & Fitness
      - Health & Fitness; Alternative Health
      - Health & Fitness; Fitness
      - Health & Fitness; Medicine
      - Health & Fitness; Mental Health
      - Health & Fitness; Nutrition
      - Health & Fitness; Sexuality
      - Kids & Family
      - Kids & Family; Education for Kids
      - Kids & Family; Parenting
      - Kids & Family; Pets & Animals
      - Kids & Family; Stories for Kids
      - Leisure
      - Leisure; Animation & Manga
      - Leisure; Automotive
      - Leisure; Aviation
      - Leisure; Crafts
      - Leisure; Games
      - Leisure; Hobbies
      - Leisure; Home & Garden
      - Leisure; Video Games
      - Music
      - Music; Music Commentary
      - Music; Music History
      - Music; Music Interviews
      - News
      - News; Business News
      - News; Daily News
      - News; Entertainment News
      - News; News Commentary
      - News; Politics
      - News; Sports News
      - News; Tech News
      - Religion & Spirituality
      - Religion & Spirituality; Buddhism
      - Religion & Spirituality; Christianity
      - Religion & Spirituality; Hinduism
      - Religion & Spirituality; Islam
      - Religion & Spirituality; Judaism
      - Religion & Spirituality; Religion
      - Religion & Spirituality; Spirituality
      - Science
      - Science; Astronomy
      - Science; Chemistry
      - Science; Earth Sciences
      - Science; Life Sciences
      - Science; Mathematics
      - Science; Natural Sciences
      - Science; Nature
      - Science; Physics
      - Science; Social Sciences
      - Society & Culture
      - Society & Culture; Documentary
      - Society & Culture; Personal Journals
      - Society & Culture; Philosophy
      - Society & Culture; Places & Travel
      - Society & Culture; Relationships
      - Sports
      - Sports; Baseball
      - Sports; Basketball
      - Sports; Cricket
      - Sports; Fantasy Sports
      - Sports; Football
      - Sports; Golf
      - Sports; Hockey
      - Sports; Rugby
      - Sports; Soccer
      - Sports; Swimming
      - Sports; Tennis
      - Sports; Volleyball
      - Sports; Wilderness
      - Sports; Wrestling
      - Technology
      - True Crime
      - TV & Film
      - TV & Film; After Shows
      - TV & Film; Film History
      - TV & Film; Film Interviews
      - TV & Film; TV Reviews
      - TV & Film; Film Reviews
  - type: dropdown
    id: explicit
    attributes:
      label: Explicit
      description: Does the feed contain explicit content?
      multiple: false
      options:
      - 'false'
      - 'true'
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      multiple: false
      options:
      - full
      - bonus
      - trailer
      description: What kind of episode is it?
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: How would you briefly describe the episode?
    validations:
      required: false
  - type: input
    id: season_number
    attributes:
      label: Season Number
      description: You only need to set this when you're releasing a new season.
      placeholder: '1'
    validations:
      required: false
  - type: input
    id: episode_number
    attributes:
      label: Episode Number
      description: You only need to set this when you're skipping an episode.
      placeholder: '1'
    validations:
      required: false
  - type: dropdown
    attributes:
      label: action
      multiple: false
      options:
        - create-episode
    validations:
      required: true
