name: Import Feed
description: Import a new RSS feed
title: "import: a new RSS feed"
labels:
  - "import"
body:
  - type: markdown
    attributes:
      value: |
        # Request to add import a new RSS feed
  - type: input
    id: url
    attributes:
      label: URL
      description: The feed's URL
      placeholder: ex. https://.../feed.xml
    validations:
      required: true
  - type: input
    id: feed_title
    attributes:
      label: Feed Title
      description: The feed's title
      placeholder: This is the podcast's name
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Website
      description: The feed's website URL
      placeholder: https://.../
    validations:
      required: false
  - type: dropdown
    attributes:
      label: action
      multiple: false
      options:
        - import-feed
    validations:
      required: true
