name: Publish updates to Github Pages
permissions:
  id-token: write
  pages: write
on:
  push:
    paths-ignore:
    - etc/feed.opml
    - dist/uploads/**
    branches:
    - main
    - master
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Validate the updated file
      run: make build
    - name: Archive artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: dist/public
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
